# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa26acfe2ec0d9f4a06c7e3e2fda9b6469208bd81d41f8d9defdd422bb59ff45eb1533f7911e6f073a8018c4f50cb40a08be9e69c6ef0cb009bfbb74d7dfd53

test:
  secret_key_base: e8aaa83ab2c722d362549ff96593d06484613346b021b0822125d4eb9f81785062f2a92700cd64f46b77052030abf4a9072217df5fc8ce36c52e836fb744f2f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
